"""API cost calculation for outsourcing decisions.

Ported from vidur's outsourcing module for cost-based prioritization.
"""


class APICostCalculator:
    """Calculate API costs for outsourcing requests."""

    def __init__(
        self,
        input_price_per_million: float = 1.25,
        output_price_per_million: float = 10.00,
        cached_input_price_per_million: float | None = None,
    ):
        """
        Initialize the cost calculator.

        Args:
            input_price_per_million: Price per million input tokens (USD)
            output_price_per_million: Price per million output tokens (USD)
            cached_input_price_per_million: Optional discounted price per
                million cached input tokens. Defaults to the uncached input
                price, which disables any cost discount.
        """
        self._input_price_per_million = input_price_per_million
        self._output_price_per_million = output_price_per_million
        self._cached_input_price_per_million = (
            input_price_per_million
            if cached_input_price_per_million is None
            else cached_input_price_per_million
        )

    def calculate_cost(self, input_tokens: int, output_tokens: int) -> float:
        """
        Calculate API cost based on token counts.

        Args:
            input_tokens: Number of input tokens
            output_tokens: Number of output tokens

        Returns:
            Total API cost in USD
        """
        return self.calculate_cost_with_cache(
            input_tokens=input_tokens,
            cached_input_tokens=0,
            output_tokens=output_tokens,
        )

    def calculate_cost_with_cache(
        self,
        input_tokens: int,
        cached_input_tokens: int,
        output_tokens: int,
    ) -> float:
        """Calculate API cost with cached-input pricing.

        Args:
            input_tokens: Total input tokens sent to the remote API.
            cached_input_tokens: Input tokens billed at cached-input price.
            output_tokens: Output tokens generated by the remote API.

        Returns:
            Total API cost in USD.
        """
        return self.calculate_cost_breakdown(
            input_tokens=input_tokens,
            cached_input_tokens=cached_input_tokens,
            output_tokens=output_tokens,
        )["total_cost_usd"]

    def calculate_cost_breakdown(
        self,
        input_tokens: int,
        cached_input_tokens: int,
        output_tokens: int,
    ) -> dict:
        """Return token and dollar breakdown for remote API billing."""
        input_tokens = max(0, int(input_tokens))
        output_tokens = max(0, int(output_tokens))
        cached_input_tokens = min(input_tokens, max(0, int(cached_input_tokens)))
        uncached_input_tokens = input_tokens - cached_input_tokens

        uncached_input_cost = (
            uncached_input_tokens / 1_000_000
        ) * self._input_price_per_million
        cached_input_cost = (
            cached_input_tokens / 1_000_000
        ) * self._cached_input_price_per_million
        output_cost = (output_tokens / 1_000_000) * self._output_price_per_million

        return {
            "input_tokens": input_tokens,
            "uncached_input_tokens": uncached_input_tokens,
            "cached_input_tokens": cached_input_tokens,
            "output_tokens": output_tokens,
            "uncached_input_cost_usd": uncached_input_cost,
            "cached_input_cost_usd": cached_input_cost,
            "output_cost_usd": output_cost,
            "total_cost_usd": uncached_input_cost + cached_input_cost + output_cost,
        }
